<?php

if (!defined('ABSPATH'))
    die('Restricted Access');

class JSVehicleManagerUser {

    private $currentuser = null;
    
    function __construct() {
        $db = new jsvehiclemanagerdb();
        if (is_user_logged_in()) { // wp user logged in
            $wpuserid = get_current_user_id();
            if (!is_numeric($wpuserid))
                return false;
            $query = "SELECT * FROM `#__js_vehiclemanager_users` WHERE uid = " . $wpuserid;
            $db->setQuery($query);
            $currentuser = $db->loadObject();
            $jsvehiclemanager_registerform = JSVEHICLEMANAGERrequest::getVar('jsvehiclemanager_autoz_register_nonce');

            $registerform = JSVEHICLEMANAGERrequest::getVar('jsvehiclemanager_registerform','post',0);
            if($currentuser == '' AND ($jsvehiclemanager_registerform == '' && $registerform == 0) ){// inserting a record in our table
                      
                $userdata = get_userdata($wpuserid);
                $profile['id'] = '';

                $profile['name'] = $userdata->display_name;
                if($userdata->display_name == ''){
                    $profile['name'] = $userdata->user_nicename;
                }
                $profile['email'] = $userdata->user_email;
                $profile['uid'] = $wpuserid;
                $profile['created'] = date_i18n('Y-m-d H:i:s');
                $profile['status'] = 1;
                $profile['autogenerated'] = 1;
                $result = JSVEHICLEMANAGERincluder::getJSModel('user')->storeProfile($profile,2);
                if(is_numeric($result)){
                    $query = "SELECT * FROM `#__js_vehiclemanager_users` WHERE id = " . $result;
                    $db->setQuery($query);
                    $currentuser = $db->loadObject();
                }
            }
            $this->currentuser = $currentuser;
        }
    }

    function isguest() {
        if ($this->currentuser == null && !is_user_logged_in()) { // current user is guest
            return true;
        } else {
            return false;
        }
    }

    function isdisabled() {
        if ($this->currentuser != null && $this->currentuser->status == 0) { // current user is disabled
            return true;
        } else {
            return false;
        }
    }

    function uid() {
        if ($this->currentuser != null) {
            return $this->currentuser->id;
        }
    }

    function emailaddress() {
        if ($this->currentuser == null) { // current user is guest
            return false;
        } else {
            return $this->currentuser->emailaddress;
        }
    }

    function fullname() {
        if ($this->currentuser == null) { // current user is guest
            return false;
        } else {
            $name = $this->currentuser->name;
            return $name;
        }
    }
    function isJSVehicleManagerUser() {
        $db = new jsvehiclemanagerdb();
        if (is_user_logged_in()) { // wp user logged in
            $wpuserid = get_current_user_id();
            if (!is_numeric($wpuserid))
                return false;
            $query = "SELECT COUNT(id) FROM `#__js_vehiclemanager_users` WHERE uid = " . $wpuserid;
            $db->setQuery($query);
            $result = $db->loadResult();
            if ($result > 0) {
                return true;
            } else {
                return false;
            }
        }else{
            return false;
        }
    }
 
    function getjsvehiclemanageruidbyuserid($userid){
        if(!is_numeric($userid)) return false;
        $db = new jsvehiclemanagerdb();
        $query = "SELECT id FROM `#__js_vehiclemanager_users` WHERE uid = ".$userid;
        $db->setQuery($query);
        $uid = $db->loadResult();
        return $uid;
    }

    function isSeller(){
        $uid = $this->uid();
        if(!is_numeric($uid) || $uid == ''){
            return false;
        }
        $db = new jsvehiclemanagerdb();   
        $query = "SELECT COUNT(veh.id) FROM `#__js_vehiclemanager_vehicles` AS veh WHERE veh.uid = ".$uid;
        $db->setQuery($query);
        $total = $db->loadResult();
        if ($total > 0) {
            return true;
        }
        return false;
    }

    function isSellerCheck($uid){
        if(!is_numeric($uid) || $uid == ''){
            return false;
        }
        $db = new jsvehiclemanagerdb();   
        $query = "SELECT COUNT(veh.id) FROM `#__js_vehiclemanager_vehicles` AS veh WHERE veh.uid = ".$uid;
        $db->setQuery($query);
        $total = $db->loadResult();
        if ($total > 0) {
            return true;
        }
        return false;
    }
}
?>